require 'rspec'
require 'pry-byebug'
require './lib/coursegen/course/data/section'
require './lib/coursegen/course/data/toc'
require './lib/coursegen/course/data/lectures'
require './lib/coursegen/course/data/citem'
require './lib/coursegen/course/schedule/scheduler'
require './lib/coursegen/course/data/section_def'

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  #config.run_all_when_everything_filtered = true
  #config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
